W0210 23:58:15.778000 139767690551680 torch/distributed/run.py:779]
W0210 23:58:15.778000 139767690551680 torch/distributed/run.py:779] *****************************************
W0210 23:58:15.778000 139767690551680 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
W0210 23:58:15.778000 139767690551680 torch/distributed/run.py:779] *****************************************
/home/nfs/abarghi/cugraph-gnn/python/cugraph-pyg/cugraph_pyg/data/feature_store.py:190: UserWarning: Ignoring index parameter (attribute does not exist for group user)
  warnings.warn(
/home/nfs/abarghi/cugraph-gnn/python/cugraph-pyg/cugraph_pyg/data/feature_store.py:190: UserWarning: Ignoring index parameter (attribute does not exist for group user)
  warnings.warn(
/home/nfs/abarghi/cugraph-gnn/python/cugraph-pyg/cugraph_pyg/data/feature_store.py:190: UserWarning: Ignoring index parameter (attribute does not exist for group movie)
  warnings.warn(
/home/nfs/abarghi/cugraph-gnn/python/cugraph-pyg/cugraph_pyg/data/feature_store.py:190: UserWarning: Ignoring index parameter (attribute does not exist for group movie)
  warnings.warn(
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/nfs/abarghi/cugraph-gnn/python/cugraph-pyg/cugraph_pyg/examples/movielens_mnmg.py", line 412, in <module>
[rank1]:     edge_label_index=(('usr','rates','movie'), eli_test)
[rank1]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: TypeError: unsupported operand type(s) for ** or pow(): 'tuple' and 'dict'
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/nfs/abarghi/cugraph-gnn/python/cugraph-pyg/cugraph_pyg/examples/movielens_mnmg.py", line 412, in <module>
[rank0]:     edge_label_index=(('usr','rates','movie'), eli_test)
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: TypeError: unsupported operand type(s) for ** or pow(): 'tuple' and 'dict'
W0210 23:58:35.123000 139767690551680 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 4122550 closing signal SIGTERM
E0210 23:58:35.287000 139767690551680 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 4122549) of binary: /home/nfs/abarghi/miniforge4/envs/rapids/bin/python
Traceback (most recent call last):
  File "/home/nfs/abarghi/miniforge4/envs/rapids/bin/torchrun", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nfs/abarghi/miniforge4/envs/rapids/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/nfs/abarghi/miniforge4/envs/rapids/lib/python3.12/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/nfs/abarghi/miniforge4/envs/rapids/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/nfs/abarghi/miniforge4/envs/rapids/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nfs/abarghi/miniforge4/envs/rapids/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
python/cugraph-pyg/cugraph_pyg/examples/movielens_mnmg.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-02-10_23:58:35
  host      : dgx19.aselab.nvidia.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4122549)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
